version: '2.4'

services:
  alice:
    hostname: alice
    image: h1994st/sec_eval
    privileged: true
    tty: true
    environment:
      MY_NAME: alice
    networks:
      testnet:
        ipv4_address: 172.50.1.2
    volumes:
      - .:/code
      - /var/run/dbus:/var/run/dbus
    cpuset: '0'
    cpus: '0.01'
    mem_limit: '50MB'
    mac_address: 02:42:ac:11:00:02
  bob:
    hostname: bob
    image: h1994st/sec_eval
    privileged: true
    tty: true
    environment:
      MY_NAME: bob
    networks:
      testnet:
        ipv4_address: 172.50.1.3
    volumes:
      - .:/code
      - /var/run/dbus:/var/run/dbus
    cpuset: '0'
    cpus: '0.01'
    mem_limit: '50MB'
    mac_address: 02:42:ac:11:00:03

networks:
  testnet:
    ipam:
      driver: default
      config:
        - subnet: 172.50.1.0/24
